kind: Service 
apiVersion: v1 
metadata: 
  name: my-service 
spec: 
  type: LoadBalancer 
  selector: 
    run: server-app1 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 8000 
