kind: Service 
apiVersion: v1 
metadata: 
  name: julia-service 
spec: 
  type: LoadBalancer 
  selector: 
    run: julia-server 
  ports: 
  - protocol: "TCP" 
    port: 80 
    targetPort: 8000 
