apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: julia-server
  labels: 
    run: julia-server
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      run: julia-server 
  template: 
    metadata: 
      labels: 
        run: julia-server
    spec: 
      containers: 
      - image: gcr.io/dockerprojectid/server-app:v7
        name: julia-server 
        ports: 
        - containerPort: 8000 
